KONFIGURASI AWAL ORACLE DATABASE XE (EXPRESS EDITION)
-----------------------------------------------------

1. VERIFIKASI
Cek Status Layanan:
Gunakan Services.msc untuk memastikan layanan OracleXEPDB1 dan OracleServiceXE berjalan.

Cek Listener:
--bash
lsnrctl status
Pastikan listener aktif pada port default (1521).

2. AKSES DATABASE
Login menggunakan SQL*Plus atau tool lain (SQL Developer, DBeaver):
--bash
sqlplus / as sysdba

Cek Database Berjalan:
--sql
SELECT INSTANCE_NAME, STATUS FROM V$INSTANCE;

Jika belum berjalan, start database:
--sql
STARTUP;

3. KONFIGURASI AWAL
A. Cek Versi Database:
--sql
SELECT * FROM V$VERSION;

B. Cek Container Database (CDB):
--sql
SELECT NAME, CDB FROM V$DATABASE;
Oracle XE menggunakan Container Database (CDB).

4. MEMBUKA PDB
Default PDB di Oracle XE adalah XEPDB1.
Buka PDB jika belum aktif:
--sql
ALTER PLUGGABLE DATABASE XEPDB1 OPEN;

Verifikasi PDB Terbuka:
--sql
SHOW PDBS;

5. BUAT USER BARU
Buat user untuk kebutuhan aplikasi:
--sql
CREATE USER project_user IDENTIFIED BY password
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS;

Penjelasan:
project_user: Nama user.
password: Password untuk user.

Berikan hak akses:
--sql 
GRANT CONNECT, RESOURCE TO project_user;
Login ke PDB menggunakan user ini:

--bash
sqlplus project_user/password@localhost/XEPDB1

6. MENGELOLA TABLESPACE
Cek Tablespace yang Ada:
--sql
SELECT TABLESPACE_NAME, STATUS FROM DBA_TABLESPACES;

Buat tablespace baru jika dibutuhkan:
--sql
CREATE TABLESPACE app_tbs
DATAFILE 'C:\opt\oracle\oradata\XEPDB1\app_tbs01.dbf' 
SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

Berikan default tablespace untuk user:
--sql
ALTER USER project_user DEFAULT TABLESPACE app_tbs;

7. MENGAKSES DAN MENGUJI KONEKSI
Cek TNSNAMES.ORA: Pastikan file tnsnames.ora (lokasi default: $ORACLE_HOME\network\admin\tnsnames.ora) sudah mengandung entry untuk XEPDB1:
--plaintext
XEPDB1 =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = XEPDB1)
    )
  )

Uji Koneksi:
--bash
sqlplus project_user/password@XEPDB1

8. PRAKTIK PENGELOLAAN DATA
A. Membuat Tabel
Login dengan user project_user dan buat tabel:
--sql
CREATE TABLE Test (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAMA VARCHAR2(20),
    UMUR NUMBER,
    Alamat VARCHAR2(100),
);

Masukkan data:
--sql
INSERT INTO Test (NAMA, UMUR, ALAMAT) VALUES ('Budi', 20, 'Jl. Pahlawan, 10120');
SELECT * FROM Test;

9. OPSI OPSIONAL: KONFIGURASI APLIKASI
Oracle SQL Developer: Gunakan tool ini untuk GUI akses database.
DBeaver: Tool alternatif untuk manajemen database.
Integrasi Aplikasi: Pastikan aplikasi (Java, Python, atau lainnya) menggunakan driver JDBC/ODBC untuk koneksi.
_________________________________________________________________________________________________________
___________________________________________________________________________________________________________________________________________________________________________________________

LANGKAH-LANGKAH MEMBUAT PLUGGABLE DATABASE (PDB):
----------------------------------------------

1. Persiapan Awal
Sebelum membuat PDB baru, pastikan:
-- Memiliki akses ke Container Database (CDB) dengan akun administrator seperti SYS atau akun dengan hak CREATE PLUGGABLE DATABASE.
-- Direktori fisik untuk menyimpan datafile PDB baru sudah ada atau dapat dibuat secara otomatis.

2. Login ke CDB
--Login ke Container Database (CDB) menggunakan sqlplus:
sqlplus sys@XE as sysdba
--Atau, jika tidak menggunakan listener:
sqlplus / as sysdba
--Setelah login, pastikan  berada di CDB root container dengan perintah:
SHOW CON_NAME;
--Hasilnya harus menunjukkan CDB$ROOT. Jika bukan, pindah ke root dengan:
ALTER SESSION SET CONTAINER = CDB$ROOT;

3. Buat Pluggable Database Baru
--Gunakan perintah berikut untuk membuat PDB baru. Ini adalah contoh umum:
CREATE PLUGGABLE DATABASE XEPDB1
ADMIN USER pdb_admin IDENTIFIED BY admin_password
FILE_NAME_CONVERT = ('C:\app\oracle\oradata\XE\pdbseed\', '\app\oracle\oradata\XE\XEPDB2\');
--XEPDB2: Nama PDB baru yang akan dibuat.
--ADMIN USER pdb_admin: Admin user untuk PDB baru.
--IDENTIFIED BY admin_password: Password untuk admin user.
--FILE_NAME_CONVERT: Menentukan lokasi datafile PDB baru. Path pertama menunjukkan lokasi datafile template (PDB$SEED), dan Path kedua menunjukkan lokasi PDB baru.

4. Buka PDB Baru
--Setelah PDB dibuat, secara default statusnya adalah MOUNTED. Buka PDB dengan perintah berikut:
ALTER PLUGGABLE DATABASE XEPDB2 OPEN;
--Untuk membuka PDB secara otomatis setiap kali database dimulai, tambahkan ke SAVE STATE:
ALTER PLUGGABLE DATABASE XEPDB2 SAVE STATE;

5. Verifikasi PDB Baru
--Periksa apakah PDB baru berhasil dibuat dan terbuka:
SHOW PDBS;
--Hasilnya akan menampilkan daftar PDB beserta statusnya, misalnya:
CON_ID CON_NAME       OPEN MODE  RESTRICTED
------ -------------- ---------- ----------
     2 PDB$SEED       READ ONLY  NO
     3 XEPDB2         READ WRITE NO

6. Koneksi ke PDB Baru
--Untuk mengakses PDB baru, buat koneksi menggunakan nama PDB, misalnya:
sqlplus pdb_admin@XEPDB2
--Atau, jika tidak menggunakan listener, gunakan:
sqlplus pdb_admin
--Pastikan  berada di PDB dengan perintah:
SHOW CON_NAME;
--Hasilnya harus menunjukkan XEPDB2.
___________________________________________________________________________________________________________________________________________________________________________________________
___________________________________________________________________________________________________________________________________________________________________________________________

LANGKAH-LANGKAH MEMBUAT TABLESPACE DI PDB:
------------------------------------------

1. Masuk sebagai DBA, menggunakan akun dengan hak akses SYSDBA (misalnya akun SYS atau SYSTEM) dengan CMD:
sqlplus sys/sys@XEPDB2 as sysdba

2. Periksa Tablespace yang Ada:
SELECT TABLESPACE_NAME FROM DBA_TABLESPACES;

3. Membuat Tablespace baru bernama PROJECT2_TBS:
CREATE TABLESPACE PROJECT2_TBS
DATAFILE 'C:\PROJECT2\DATAFILES\project2_tbs01.dbf'
SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

4. Menetapkan Default Tablespace untuk User PROJECT2,
ALTER USER PROJECT2 DEFAULT TABLESPACE PROJECT2_TBS;

5. Memberikan Quota pada Tablespace untuk user PROJECT2,
Memberikan quota tak terbatas:
ALTER USER PROJECT2 QUOTA UNLIMITED ON PROJECT2_TBS;
Memberikan kuota terbatas, misalnya 100 MB:
ALTER USER PROJECT2 QUOTA 100M ON PROJECT2_TBS;

6. Memberikan Hak Akses kepada USER,
Untuk memberikan hak akses kepada user PROJECT2, misalnya hak untuk membuat tabel atau menghubungkan ke database, jalankan perintah berikut:

Hak Akses Dasar
GRANT CONNECT, RESOURCE TO PROJECT2;

Hak Akses Khusus untuk TABLESPACE
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER TO PROJECT2;

Verifikasi Akses
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'PROJECT2'; --Privilege pada objek (tabel, view, dll.). Contoh: SELECT, INSERT, EXECUTE, READ, WRITE. *Jika ingin memeriksa apakah user memiliki hak akses pada tabel tertentu.
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'PROJECT2'; --System privilege. Contoh: CREATE TABLE, CREATE VIEW, ALTER SESSION. *Jika ingin memeriksa apakah user dapat membuat tabel.
SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'PROJECT2'; --Role yang dimiliki. Contoh: Role seperti CONNECT, RESOURCE, DBA. *Jika ingin melihat role yang dimiliki oleh USER.

7. Memeriksa Default Tablespace untuk User PROJECT2,
Untuk memastikan bahwa default tablespace telah diubah dengan benar, jalankan query:
SELECT USERNAME, DEFAULT_TABLESPACE, TEMPORARY_TABLESPACE 
FROM DBA_USERS 
WHERE USERNAME = 'PROJECT2';
Jika berhasil,  akan melihat tablespace yang baru diatur untuk user PROJECT2.

8. Cek Ketersediaan Tablespace dan USER,
Jika  ingin memeriksa semua users dan tablespace yang terkait, gunakan:
SELECT USERNAME, DEFAULT_TABLESPACE, TEMPORARY_TABLESPACE 
FROM DBA_USERS;
___________________________________________________________________________________________________________________________________________________________________________________________
___________________________________________________________________________________________________________________________________________________________________________________________
